FROM continuumio/miniconda3:4.10.3-alpine

COPY env.yaml /tmp/
COPY rootkey.csv /app/

COPY lambda2_local.py /app/
COPY dash_app_local.py /app/

# Using conda
# RUN conda env create --file /tmp/env.yaml

RUN conda install --yes --freeze-installed -c conda-forge \
    pandas \
    numpy \
    boto3 \
    python-json-logger \
    flask \
    httpstan==4.6.1 \
    pystan==2.19.1.1 \
    dash \
    dash-html-components \
    dash-core-components \
    plotly \
    && conda clean -afy

RUN conda install --yes --freeze-installed -c conda-forge \
    prophet \
    && conda clean -afy \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.pyc' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete

# SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]
# ENV PATH /opt/conda/envs/myenv/bin:$PATH
# RUN /bin/bash -c "source activate myenv"

# RUN conda install prophet -c conda-forge
RUN echo "Check prophet is installed"
RUN python -c "from prophet import Prophet"

# Using pip

# RUN pip install --upgrade pip
# RUN pip install -r /tmp/requirements_1.txt
# RUN pip install -r /tmp/requirements_httpstan.txt
# RUN pip install -r /tmp/requirements_pystan.txt
# RUN pip install -r /tmp/requirements_prophet.txt

WORKDIR /app

ENTRYPOINT [ "python" ]
CMD [ "/app/dash_app_local.py" ]