name: CI/CD

env:
  polygon_API_key: ${{ secrets.polygon_API_key }}

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: make install

      - name: Run tests
        run: make test
